api:
  listen-addr: "*:9000"
  serve-docs: true

db:
  # Syntax: https://www.postgresql.org/docs/9.5/libpq-connect.html#LIBPQ-CONNSTRING
  conn-string: "host=localhost dbname=ednadb user=ednauser password=ednapass"
  max-connection: 200
