# SPDX-FileCopyrightText: 2021 Serokell <https://serokell.io>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Config intended to be used by developers in daily work
api:
  listen-addr: "*:9000"
  serve-docs: true

db:
  # Syntax: https://www.postgresql.org/docs/9.5/libpq-connect.html#LIBPQ-CONNSTRING
  conn-string: "host=localhost port=5432 dbname=ednadb user=ednauser password=ednapass"
  max-connections: 200
  # Optional value used if you want to init DB on start
  initialisation:
    # Two options of DB initialisation from the app:
    # * "enable" will run init script on the app start,
    # * "enable-with-drop" will run drop script before init
    mode: "enable"
    init-script: "./sql/init.sql"

# Other possible values: "prod" and "nothing".
logging: "dev"
