# SPDX-FileCopyrightText: 2021 Serokell <https://serokell.io>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Note that CI/CD pipelines use Nix to build backend.
# They use haskell.nix which depends on hackage.nix and stackage.nix which
# contain snapshots of Hackage and Stackage respectively.
# If you update resolver or any dependency to a version not present in any of
# these snapshots, you need to upadte the revision of the respective snapshot.
# Revisions are pinned in the flake.lock file in the root of the repo.
# In order to update it, you need to have a very recent (unstable) nix with
# support for flakes.
# If your nix is not sufficiently recent, you can do
# > nix-shell -I nixpkgs=channel:nixpkgs-unstable -p nixFlake
# and then within this shell run
# > nix --experimental-features 'nix-command flakes' flake update --update-input hackage

# Also if you update something in this file, most likely you should run
# `scripts/generate-cabal-files.sh`.

resolver: lts-17.2

packages:
- .

extra-deps:
- beam-core-0.9.0.0
- beam-postgres-0.5.0.0
- beam-migrate-0.5.0.0
- dependent-map-0.4.0.0
- dependent-sum-0.7.1.0
- constraints-extras-0.3.0.2
- network-uri-json-0.4.0.0
# servant-util is in dirty state and is not on Hackage.
# Perhaps it should be renamed and maybe even split into multiple packages
# with more precise goals.
# It's developed by us, so we are quite confident in it, that's why we are using
# it even though it's not ready yet.
- git: https://github.com/serokell/servant-util
  commit: 3dff2de34cce90c4d1dab68e03d30f8939fd52ca # not master
  subdirs:
    - servant-util

# beam-core currently doesn't support aeson from the resolver we are using
allow-newer: true
