# SPDX-FileCopyrightText: 2021 Serokell <https://serokell.io>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

steps:
# Checks for the whole repo
  - label: check trailing whitespace
    commands:
      - bash -c groups
      - bash -c ls -lah /run/user/1155/docker.sock
      - docker run hello-world
