steps:
  - label: check trailing whitespace
    commands:
      - .buildkite/check-trailing-whitespace.sh
  - label: validate cabal files
    commands:
      - nix-shell --run 'cd backend && scripts/validate-cabal-files.sh'
  - label: backend server
    commands:
      - nix-build -A packages.x86_64-linux.backend-server
  - label: backend lib
    commands:
      - nix-build -A packages.x86_64-linux.backend-lib
  - label: backend test
    commands:
      - nix-build -A checks.x86_64-linux.backend-test
  - label: backend image
    commands:
      - nix-build -A packages.x86_64-linux.docker-backend
      - buildkite-agent artifact upload "$(readlink -f result)"
  - label: backend hlint
    commands:
      - nix-shell --run 'hlint backend -j --hint backend/.hlint.yaml'
  - label: frontend build
    commands:
      - nix-build -A packages.x86_64-linux.frontend
  - label: frontend image
    commands:
      - nix-build -A packages.x86_64-linux.docker-frontend
      - buildkite-agent artifact upload "$(readlink -f result)"
  - label: frontend tscompile
    commands:
      - nix-build -A checks.x86_64-linux.frontend-tscompile
  - label: frontend tslint
    commands:
      - nix-build -A checks.x86_64-linux.frontend-tslint
  - label: frontend stylelint
    commands:
      - nix-build -A checks.x86_64-linux.frontend-stylelint
  - wait
  - label: Deploy staging
    commands:
      - nix-shell --run 'deploy .#staging'
    branches: "master"
  - label: Deploy demo
    commands:
      - nix-shell --run 'deploy .#demo'
    branches: "demo"
  - label: Push backend image to registry
    commands:
      - nix-shell --run 'scripts/docker-push.sh docker-archive:$(nix-build -A packages.x86_64-linux.docker-backend) docker://ghcr.io/serokell/edna-backend:latest'
    branches: "master"
  - label: Push frontend image to registry
    commands:
      - nix-shell --run 'scripts/docker-push.sh docker-archive:$(nix-build -A packages.x86_64-linux.docker-frontend) docker://ghcr.io/serokell/edna-frontend:latest'
    branches: "master"
