# SPDX-FileCopyrightText: 2021 Serokell <https://serokell.io>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

# Config for docker-compose-based local deployment
# NOTE: All these options can be overwritten by env variables
api:
  listen-addr: "*:9000"
  serve-docs: true

db:
  # Syntax: https://www.postgresql.org/docs/9.5/libpq-connect.html#LIBPQ-CONNSTRING
  # NOTE: `conn-string` is empty here, because we use env variables for
  #       docker, so .env file have all needed variables to build this one.
  conn-string: ""
  max-connections: 200
  # Optional value that we use to init DB on start
  initialisation:
    # Two options of DB initialisation from the app:
    # * "enable" will run init script on the app start,
    # * "enable-with-drop" will run drop script before init
    mode: "enable"
    # Inside the Docker image `init.sql` is available in the root
    init-script: "/init.sql"

# Other possible values: "prod" and "nothing".
logging: "dev"
